package com.mrmrscart.orderspaymentsservice.feign.pojo;

public enum ECategory {

	FIXED_COMMISSION, ZERO_COMMISSION, CATEGORY, SET, SUB_CATEGORY, VARIATION, VARIATION_OPTION, STANDARD_VARIATION, OTHER_VARIATION
}
