package com.mrmrscart.helpandsupportservice.entity;

public enum EIssueType {
	ORDER_RELATED_ISSUE, 
	RETURN_AND_REFUND, 
	LOGISTICS_RELATED_ISSUE,
	PAYMENT_TRANSACTION_RELATED_ISSUE,
	CANCELLATION_AND_REFUND, 
	PROFILE_RELATED_ISSUE,
	PAYMENT_SETTLEMENT_ISSUE, 
	ACCOUNT_MANAGEMENT_ISSUE, 
	OTHERS
}
