spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/api/v1/auth/**
      - id: help-and-support-service
        uri: lb://help-and-support-service
        predicates:
        - Path=/api/v1/help-and-support/**
      - id: notification-report-log-service
        uri: lb://notification-report-log-service
        predicates:
        - Path=/api/v1/notification/**  
      - id: orders-payments-service
        uri: lb://orders-payments-service
        predicates:
        - Path=/api/v1/order-payment/**
      - id: product-categories-service
        uri: lb://product-categories-service
        predicates:
        - Path=/api/v1/products/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/v1/users/**

